export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'