export const GET_CART_REQUEST = 'GET_CART_REQUEST'
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS'
export const GET_CART_ERROR = 'GET_CART_ERROR'

export const POST_CART_REQUEST = 'POST_CART_REQUEST'
export const POST_CART_SUCCESS = 'POST_CART_SUCCESS'
export const POST_CART_ERROR =   'POST_CART_ERROR'

// export const GET_CART_DATA = 'GET_CART_DATA'
// export const GET_CART_DATA = 'GET_CART_DATA'